# MIT License

from collections import OrderedDict

bone_list = ['ControlNode', 'ParentNode', 'Center', 'CenterTip', 'Groove', 'Waist', 'EyesTip',
             'LowerBodyTip', 'UpperBody2Tip', 'GrooveTip', 'NeckTip']
bone_list_with = ['_Shadow_', '_Dummy_', 'Dummy_', 'WaistCancel', 'LegIKParent', 'LegIK',
                  'ShoulderP_', 'EyeTip_', 'HandDummy_', 'SleeveShoulderIK_', 'Cf_O_Root_']
bone_list_parenting = {
    'Spine': 'Hips',
    'Chest': 'Spine',
    'Upper Chest': 'Chest',
    'Neck': 'Upper Chest',
    'Head': 'Neck',
    'Left shoulder': 'Upper Chest',
    'Right shoulder': 'Upper Chest',
    'Left arm': 'Left shoulder',
    'Right arm': 'Right shoulder',
    'Left elbow': 'Left arm',
    'Right elbow': 'Right arm',
    'Left wrist': 'Left elbow',
    'Right wrist': 'Right elbow',
    'Left leg': 'Hips',
    'Right leg': 'Hips',
    'Left knee': 'Left leg',
    'Right knee': 'Right leg',
    'Left ankle': 'Left knee',
    'Right ankle': 'Right knee',
    'Left toe': 'Left ankle',
    'Right toe': 'Right ankle',

    'Left leg 2': 'Left leg',
    'Right leg 2': 'Right leg',

    'Thumb0_L': 'Left wrist',
    'IndexFinger1_L': 'Left wrist',
    'MiddleFinger1_L': 'Left wrist',
    'RingFinger1_L': 'Left wrist',
    'LittleFinger1_L': 'Left wrist',

    'Thumb1_L': 'Thumb0_L',
    'IndexFinger2_L': 'IndexFinger1_L',
    'MiddleFinger2_L': 'MiddleFinger1_L',
    'RingFinger2_L': 'RingFinger1_L',
    'LittleFinger2_L': 'LittleFinger1_L',

    'Thumb2_L': 'Thumb1_L',
    'IndexFinger3_L': 'IndexFinger2_L',
    'MiddleFinger3_L': 'MiddleFinger2_L',
    'RingFinger3_L': 'RingFinger2_L',
    'LittleFinger3_L': 'LittleFinger2_L',

    'Thumb0_R': 'Right wrist',
    'IndexFinger1_R': 'Right wrist',
    'MiddleFinger1_R': 'Right wrist',
    'RingFinger1_R': 'Right wrist',
    'LittleFinger1_R': 'Right wrist',

    'Thumb1_R': 'Thumb0_R',
    'IndexFinger2_R': 'IndexFinger1_R',
    'MiddleFinger2_R': 'MiddleFinger1_R',
    'RingFinger2_R': 'RingFinger1_R',
    'LittleFinger2_R': 'LittleFinger1_R',

    'Thumb2_R': 'Thumb1_R',
    'IndexFinger3_R': 'IndexFinger2_R',
    'MiddleFinger3_R': 'MiddleFinger2_R',
    'RingFinger3_R': 'RingFinger2_R',
    'LittleFinger3_R': 'LittleFinger2_R',

    # Special cases
    'M_Head_Copy': 'Head',

    # 'J_L_Eye_UpperMiddle_001': 'Head',
    # 'J_L_Eye_UnderOuter_001': 'Head',
    # 'J_L_Eye_UnderMiddle_001': 'Head',
    # 'J_L_Eye_UnderInner_001': 'Head',
    # 'J_L_Eye_UnderCorner_001': 'Head',
    # 'J_L_Eye_UpperInner_001': 'Head',
    # 'J_L_Eye_UpperOuter_001': 'Head',
    # 'J_L_Eye_UpperCorner_001': 'Head',
}
dont_delete_these_bones = [
    'Hips', 'Spine', 'Chest', 'Upper Chest', 'Neck', 'Head',
    'Left leg', 'Left knee', 'Left ankle', 'Left toe',
    'Right leg', 'Right knee', 'Right ankle', 'Right toe',
    'Left shoulder', 'Left arm', 'Left elbow', 'Left wrist',
    'Right shoulder', 'Right arm', 'Right elbow', 'Right wrist',
    'OldRightEye', 'OldLeftEye', 'LeftEye', 'RightEye', 'Eye_L', 'Eye_R',
    'Left leg 2', 'Right leg 2',

    'Thumb0_L', 'Thumb1_L', 'Thumb2_L',
    'IndexFinger1_L', 'IndexFinger2_L', 'IndexFinger3_L',
    'MiddleFinger1_L', 'MiddleFinger2_L', 'MiddleFinger3_L',
    'RingFinger1_L', 'RingFinger2_L', 'RingFinger3_L',
    'LittleFinger1_L', 'LittleFinger2_L', 'LittleFinger3_L',

    'Thumb0_R', 'Thumb1_R', 'Thumb2_R',
    'IndexFinger1_R', 'IndexFinger2_R', 'IndexFinger3_R',
    'MiddleFinger1_R', 'MiddleFinger2_R', 'MiddleFinger3_R',
    'RingFinger1_R', 'RingFinger2_R', 'RingFinger3_R',
    'LittleFinger1_R', 'LittleFinger2_R', 'LittleFinger3_R',

    'Breast_L', 'Breast_R',
]
dont_delete_these_main_bones = [
    'Hips', 'Spine', 'Chest', 'Upper Chest', 'Neck', 'Head',
    'Left leg', 'Left knee', 'Left ankle', 'Left toe',
    'Right leg', 'Right knee', 'Right ankle', 'Right toe',
    'Left shoulder', 'Left arm', 'Left elbow', 'Left wrist',
    'Right shoulder', 'Right arm', 'Right elbow', 'Right wrist',
    'LeftEye', 'RightEye', 'Eye_L', 'Eye_R',
    'Left leg 2', 'Right leg 2',

    'Thumb0_L', 'Thumb1_L', 'Thumb2_L',
    'IndexFinger1_L', 'IndexFinger2_L', 'IndexFinger3_L',
    'MiddleFinger1_L', 'MiddleFinger2_L', 'MiddleFinger3_L',
    'RingFinger1_L', 'RingFinger2_L', 'RingFinger3_L',
    'LittleFinger1_L', 'LittleFinger2_L', 'LittleFinger3_L',

    'Thumb0_R', 'Thumb1_R', 'Thumb2_R',
    'IndexFinger1_R', 'IndexFinger2_R', 'IndexFinger3_R',
    'MiddleFinger1_R', 'MiddleFinger2_R', 'MiddleFinger3_R',
    'RingFinger1_R', 'RingFinger2_R', 'RingFinger3_R',
    'LittleFinger1_R', 'LittleFinger2_R', 'LittleFinger3_R',
]
bone_list_rename_unknown_side = {
    'Shoulder': 'shoulder',
    'Shoulder_001': 'shoulder',
}
bone_reweigth_to_parent = [
    r'ShoulderC_\L',
    r'Arm_\Left_Shoulder_Adj_1',
    r'Arm_\Left_Shoulder_Adj_2',
    r'Arm_\Left_Shoulder_Adj_3',
    r'Arm_\Left_Shoulder_Adj_4',
    r'Arm_\Left_Shoulder_2_Adj_1',
    r'Arm_\Left_Shoulder_2_Adj_2',
    r'Arm_\Left_Shoulder_2_Adj_3',
    r'Arm_\Left_Shoulder_2_Adj_4',
    r'Arm_\Left_Elbow_Adj_1',
    r'Arm_\Left_Elbow_Adj_2',
    r'Arm_\Left_Elbow_Adj_3',
    r'Arm_\Left_Elbow_Adj_4',
    r'Leg_\Left_Knee_Adj_1',
    r'Leg_\Left_Knee_Adj_2',
    r'Leg_\Left_Knee_Adj_3',
    r'Leg_\Left_Knee_Adj_4',
    r'ArmTwist_\L',
    r'H(\L)_0',
    r'H(\L)_1',
    r'H(\L)_2',
    r'H(\L)_3',
    r'Knee1_\L',
    r'Knee1_2_\L',
    r'Knee2_\L',
    r'Knee2_2_\L',
    r'Knee3_\L',
    r'Knee3_2_\L',
    r'Knee4_\L',
    r'Knee4_2_\L',
    r'Knee5_\L',
    r'Knee5_2_\L',
    r'Knee6_\L',
    r'Knee6_2_\L',
    r'Knee7_\L',
    r'Knee7_2_\L',
    'AbdomenLower',
    'ChestUpper',
    'Back_Low',
    'Back_Mid',
]
bone_list_conflicting_names = [
    ([r'\L_Clavicle'], r'\L_Shoulder', r'Arm_\L'),
    ([r'\LeftCollar'], r'\LeftShoulder', r'Arm_\L'),
    ([r'\Left_Collar'], r'\Left Shoulder', r'Arm_\L'),
    ([r'\LeftUpLeg'], r'\LeftLeg', r'Knee_\L'),
    ([r'\Left_Foot'], r'\Left_Foot_EX', r'Toe_\L'),

    ([r'Lower_Arm_\L'], r'Elbow_\L', r'Elbow_\L_Ignore'),
    ([r'Lower_Leg_\L'], r'Knee_\L', r'Knee_\L_Ignore'),
    (['Pelwas'], 'Spine', 'Pelwas2'),

    ([r'ArmFor_Correction_\L'], r'Arm_\L', r'ArmTwist5_\L'),
    ([r'ElbowFor_Correction_\L'], r'Elbow_\L', r'HandTwist5_\L'),

    ([r'\Leftcollar'], r'\Leftshoulder', r'\Leftarm'),

    ([r'Shoulder+_\L'], r'Shoulder_\L', r'Shoulder2_\L'),

    ([r'Tg_\L'], r'Leg_\L', r'Knee_\L'),

    ([r'ShoulderParent1_\L', r'ShoulderParent2_\L'], r'Shoulder2_\L', r'\Left shoulder'),
    ([r'ArmParent1_\L', r'ArmParent2_\L'], r'Arm2_\L', r'\Left arm'),
    ([r'ElbowParent1_\L', r'ElbowParent2_\L'], r'Elbow2_\L', r'\Left elbow'),
    ([r'WristParent1_\L', r'WristParent2_\L'], r'Wrist2_\L', r'\Left wrist'),

    ([r'Wind0_\L'], r'Shoulder2_\L', r'\Left shoulder'),
    ([r'Wind0_\L'], r'Arm2_\L', r'\Left arm'),
    ([r'Wind0_\L'], r'Elbow2_\L', r'\Left elbow'),
    ([r'Wind0_\L'], r'Wrist2_\L', r'\Left wrist'),

    ([r'\LeftAnkle'], r'\LeftFoot', r'\Left ankle'),

    ([r'Arm_\L'], r'Arm+_\L', r'\Left arm'),
    ([r'Elbow_\L'], r'Elbow+_\L', r'\Left elbow'),
    ([r'Wrist_\L'], r'Wrist+_\L', r'\Left wrist'),
    ([r'Wrist_\L'], r'Wrist+F_\L', r'\Left wrist'),

    (['Strengthen_The_Spine'], 'Spine1', 'Backbone1'),
    (['Strengthen_The_Spine'], 'Spine2', 'Backbone2'),
    (['Strengthen_The_Spine'], 'Spine3', 'Backbone3'),
    (['Strengthen_The_Spine'], 'Spine4', 'Backbone4'),
    (['Strengthen_The_Spine'], 'Spine5', 'Backbone5'),
    (['Strengthen_The_Spine'], 'Spine6', 'Backbone6'),
    (['Strengthen_The_Spine'], 'Spine7', 'Backbone7'),

    ([r'\Left_Heel', r'\Left_Shin'], r'\Left_Calf', r'\Left_Leg'),
    ([r'\Left_Heel', r'\Left_Shin'], r'\Left_Foot', r'\Left_Ankle_D'),

    ([r'Tsumasaki_\L'], r'Tsumasaki_Linkage_\L', r'\Left toe'),

    ([r'\L_UpLeg'], r'\L_Leg', r'\Left knee'),
    (['Leg(L)00'], 'Leg(R)03', 'Leg(R)00_tmp'),
    (['Leg(L)03'], 'Leg(R)02', 'Leg(R)03'),
    (['Leg(L)02'], 'Leg(R)00', 'Leg(R)02'),
    (['Leg(L)00'], 'Leg(R)00_tmp', 'Leg(R)00'),

    (['Torso_1'], r'\Left_Foot', r'\Left ankle'),

    # (['Shoulder_\L', 'Shoulder_IK_Root_\L'], 'Shoulder1_WayA_\L', '\Left shoulder'),

    # Fix Koikatsu models
    ([r'Cf_D_Shoulder_\L'], r'Shoulder_\L', r'Cf_D_Shoulder2_\L'),
    (['Cf_Hit_Waist02', r'Leg_\L'], r'Shoulder_\L', r'Cf_D_Shoulder2_\L'),

    # Just rename those
    ([], 'Root_Ground', 'Ground_Root'),
    ([], 'Root_Hips', 'Hips_Root'),
    ([], 'Root_Hips_1', 'Hips_Root_1'),
    ([], 'Root_Hips_2', 'Hips_Root_2'),
    ([], 'Root_Rot', 'Rot_Root'),

    # (['Elbowb_\L', 'Elbowc_\L'], 'Elbowa_\L', 'Arm05_\L'),

    # Fix SSBU models
    (['Trans', 'Rot', 'Hip'], 'Waist', 'Spine1'),
    (['Trans', 'Rot', 'Hip'], 'Bust', 'Spine2'),
    (['Trans', 'Rot', 'Hip'], r'Shoulder\L', r'\Left arm'),
    (['Trans', 'Rot', 'Hip'], r'Arm\L', r'\Left elbow'),

    # Fix Alucard model
    (['Hip', 'S_MantleR1'], 'Bust', 'Chest'),
    (['Hip', 'S_MantleR1'], 'Waist', 'Spine'),
    (['Hip', 'S_MantleR1'], r'Clavicle\L', r'\Left shoulder'),
    (['Hip', 'S_MantleR1'], r'Shoulder\L', r'\Left arm'),
    (['Hip', 'S_MantleR1'], r'Arm\L', r'\Left elbow'),

    # Fix Detroit model
    (['Bip_UpperArmBase_L', 'Bip_ArmpitRingBase_L'], 'Bip_UpperArm_R', 'Bip_UpperArm_L'),
    (['Bip_UpperArmBase_L', 'Bip_ArmpitRingBase_L'], 'Bip_UpperArm_R_001', 'Bip_UpperArm_R'),

    # Fix fox inverted spines model
    (['Neck03', 'Bum_L', 'Upperleg01_L', 'Upperleg02_L'], 'Spine01', 'Spine5'),
    (['Neck03', 'Bum_L', 'Upperleg01_L', 'Upperleg02_L'], 'Spine02', 'Spine4'),
    (['Neck03', 'Bum_L', 'Upperleg01_L', 'Upperleg02_L'], 'Spine03', 'Spine3'),
    (['Neck03', 'Bum_L', 'Upperleg01_L', 'Upperleg02_L'], 'Spine04', 'Spine2'),
    (['Neck03', 'Bum_L', 'Upperleg01_L', 'Upperleg02_L'], 'Spine05', 'Spine1'),

    # Fix some model
    ([r'\LKnee'], r'\LLeg', r'\Left leg'),

    ([r'\L_Clav', r'\L_ShoulderMid'], r'\L_Shoulder', r'Arm_\L'),
]
bone_finger_list = [
    'Thumb0_',
    'IndexFinger1_',
    'MiddleFinger1_',
    'RingFinger1_',
    'LittleFinger1_',

    'Thumb1_',
    'IndexFinger2_',
    'MiddleFinger2_',
    'RingFinger2_',
    'LittleFinger2_',

    'Thumb2_',
    'IndexFinger3_',
    'MiddleFinger3_',
    'RingFinger3_',
    'LittleFinger3_',
]

################################
# Capitalize all bone names!
# Capitalize after each underscore!
# Replace '-' with '_'
# Replace ' ' with '_'
# Replace 'ValveBiped_' with ''
# Replace 'Bip1_' with 'Bip_'
# Replace 'Bip01_' with 'Bip_'
# Replace 'Bip001_' with 'Bip_'
# Replace '_Bone' with ''
#
# Replace New Bone Patterns:
#   Left/Right = \Left
#   L/R = \L
# Replace Old Bone Patterns:
#   Left/Right = \Left
#   left/right = \left
#   L/R = \L
#   l/r = \l
################################
bone_rename = OrderedDict()
bone_rename['Hips'] = [
    'LowerBody',
    'Lower_Body',
    'Mixamorig_Hips',
    'Pelvis',
    'B_C_Pelvis',
    'Bip_Pelvis',
    'Hip',
    'Root',
    'Hips_Root',
    'Rot_Root',
    'Sk',
    'C_Waist_1',
    'Pelwas_001',
    'Waist',
    'HipN',
    'Unused_Root_Hips',
    'Waist01',
    'Waist02',
    'Hips_Root_1',
    'Hips_Root_2',
    'Pelvis_Def',
    'J_Kosi',
    'Kosi',
    'HipMaster_01',
    'J_Bip_C_Hips',
    'J_Hip',
    'Pelvis_L',
    'Pelvis_R',
    'Root_Pelvis_1',
    'Root_X',
]
bone_rename['Spine'] = [  # This is a list of all the spine and chest bones. They will be correctly fixed
    'Spine',  # First entry!

    # MMD
    'UpperBody',
    'Upper_Body',
    'Upper_Waist',
    'UpperBody2',
    'Upper_Body_2',
    'Upper_Waist_2',
    'Waist_Upper_2',
    'UpperBody3',
    'Upper_Body_3',
    'Upper_Waist_3',
    'Waist_Upper_3',

    # Mixamo
    'Mixamorig_Spine',
    'Mixamorig_Spine0',
    'Mixamorig_Spine1',
    'Mixamorig_Spine2',
    'Mixamorig_Spine3',
    'Mixamorig_Spine4',

    # 3DMax?
	#whoever made comment above, this applies to Valve_Biped and some others.
    'Bip_Spine',
    'Bip_Spine0',
    'Bip_Spine1',
    'Bip_Spine2',
    'Bip_Spine3',
    'Bip_Spine4',
    'Bip_Spine5',
    'Bip_Spine00',
    'Bip_Spine01',
    'Bip_Spine02',
    'Bip_Spine03',
    'Bip_Spine04',
    'Bip_Spine05',
    'Bip_Spine_0',
    'Bip_Spine_1',
    'Bip_Spine_2',
    'Bip_Spine_3',
    'Bip_Spine_4',
    'Bip_Spine_5',
    'Bip_Chest',

    # Something
    'B_C_Spine',
    'B_C_Spine0',
    'B_C_Spine1',
    'B_C_Spine2',
    'B_C_Spine3',
    'B_C_Spine4',
    'B_C_Spine5',
    'B_C_Chest',

    # .Mesh
    'Spine_Lower',
    'Spine_Lower_1',
    'Spine_Lower_2',
    'Spine_Middle',
    'Spine_Upper',
    'Spine_Upper_1',
    'Spine_Upper_2',

    'J_SpineLower',
    'J_SpineUpper',

    'Abdomen',

    'Spine0',
    'Spine1',
    'Spine2',
    'Spine3',
    'Spine4',
    'Spine5',

    'Spine_0',
    'Spine_1',
    'Spine_2',
    'Spine_3',
    'Spine_4',
    'Spine_5',

    'Spine01',
    'Spine02',
    'Spine03',
    'Spine04',
    'Spine05',

    'Spine_01',
    'Spine_02',
    'Spine_03',
    'Spine_04',
    'Spine_05',

    'Spine_A',
    'Spine_B',
    'Spine_C',
    'Spine_D',
    'Spine_E',

    'SpineA',
    'SpineB',
    'SpineC',
    'SpineD',
    'SpineE',

    'Spina00',
    'Spina01',
    'Spina02',

    'J_Spine1',
    'J_Spine2',
    'J_Spine3',
    'J_Spine4',

    'Spine_Jnt_01',
    'Spine_Jnt_02',
    'Spine_Jnt_03',

    'Chest1',
    'Chest2',
    'Chest3',

    'Chest_A',
    'Chest_B',
    'Chest_C',
    'Chest_D',
    'Chest_E',

    'C_Spine_A_1',
    'C_Spine_B_1',

    'J_Bip_C_Spine',
    'J_Bip_C_Chest',
    'J_Bip_C_UpperChest',

    'Pelwas',
    'Pelwas2',
    'Ribs',

    'BODY1',
    'BODY2',

    'WaistN',
    'BustN',

    'Middle',
    'Bust',

    'SpA',
    'SpB',
    'SpC',

    'Stomach_Def',
    'Chest_Def',

    'TorsoA_01',
    'TorsoB_01',
    'TorsoC_01',

    'Torso_1',
    'Torso_2',

    'AbdomenUpper',
    'ChestLower',

    'Spine_01_X',
    'Spine_02_X',

    'J_Sebo_A',
    'J_Sebo_B',
    'J_Sebo_C',

    'Mune',

    'SpineTop',

    'UpperBodyx2',

    'Chest',

    'Upper_Chest'  # Last entry!
]
bone_rename['Neck'] = [
    'Mixamorig_Neck',
    'Head_Neck_Lower',
    'Head_Neck_Lower_1',
    'Head_Neck_Lower_2',
    'Head_Neck_Middle',
    'Bip_Neck',
    'Bip_Neck1',
    'B_C_Neck1',
    'Head_Neck',
    'J_Bip_C_Neck',
    'C_Neck_1',
    'NECK',
    'NeckN',
    'Helmet_Lower',
    'Neck_Dev',
    'Neck00',
    'Kubi',
    'J_Kubi',
    'NeckA_01',
    'J_Neck1',
    'NeckLower',
    'Neck_X',
]
bone_rename['Head'] = [
    'Mixamorig_Head',
    'Head_Neck_Upper',
    'Head_Neck_Upper_1',
    'Head_Neck_Upper_2',
    'Bip_Head',
    'Bip_Head1',
    'B_C_Head',
    'J_Bip_C_Head',
    'C_Head_1',
    'HEAD',
    'HeadN',
    'Helmet_Upper',
    'Head_01',
    'Head_001',
    'J_Head',
    'Head_X',
    'J_Kao',
]
bone_rename[r'\Left shoulder'] = [
    r'\Left_Shoulder',
    r'\LeftShoulder',
    r'Shoulder_\L',
    r'Shoulder_\Left',
    r'\LShoulder',
    r'\LShoulderN',
    r'Shoulder\L',
    r'\L_Shoulder',
    r'Mixamorig_\LeftShoulder',
    r'Arm_\Left_Shoulder',
    r'Arm_\Left_Shoulder_1',
    r'ShoulderArm_\L',
    r'Bip_\L_Clavicle',
    r'Bip_Collar_\L',
    r'B_\L_Shoulder',
    r'\LCollar',
    r'\L_Clavicle',
    r'\L_Clavicle1',
    r'\Left_Clavicle',
    r'\LeftCollar',
    r'\Left_Collar',
    r'\L_Collar',
    r'\L_Clavicle_1',
    r'\L_CBONE',
    r'Shoulder+_\L',
    r'Shol_\L',
    r'\Lf_Clavicle',
    r'Clavicle_\L',
    r'Arm_\Left_Sh_1',
    r'Shoulder(\L)_0',
    r'\L_Kata',
    r'Cf_D_Shoulder_\L',
    r'Cf_D_Shoulder2_\L',
    r'Clavicle\LT_01',
    r'J_Bip_\L_Shoulder',
    r'J_\L_Collar',
    r'J_\L_Shoulder',
    r'Clavicle\L',
    r'Bip_Clavicle_\L',
    r'\L_Clavic',
    r'J_Sako_\L',
    r'\L_ShoulderPad',
    r'Collarbone_\L',
    r'J_Clavicle_\L',
    r'\L_Clav',
    r'Clav_\L',
    r'\LClavicle',
    r'Bip_\L_Arm',
]
bone_rename[r'\Left arm'] = [
    r'\Left_Arm',
    r'\LeftArm',
    r'Arm_\L',
    r'cShrugger.\L',
    r'\LArm',
    r'\LArmA',
    r'ArmTC_\L',
    r'+_\Left_Elbow_Support',
    r'Mixamorig_\LeftArm',
    r'Arm_\Left_Shoulder_2',
    r'Bip_\L_UpperArm',
    r'Bip_UpperArm_\L',
    r'B_\L_Arm1',
    r'Upper_Arm_\L',
    r'UpperArm_\L',
    r'\Left_Upper_Arm',
    r'\LShldr',
    r'\L_UpperArm',
    r'\LeftUpArm',
    r'Uparm_\L',
    r'\L_Uparm',
    r'\L_Arm',
    r'\L_Arm_01',
    r'Arm_\Left_Arm',
    r'\L_Upperarm_1',
    r'ArmFor_Correction_\L',
    r'\L_ARM1',
    r'Arm\L1',
    r'\LShoulderJ',
    r'\Lf_Shoulder',
    r'Arm_Upper_\L',
    r'Arm_\Left_Sh_2',
    r'\Larm1',
    r'Shoulder(\L)_1',
    r'\L_Ude',
    r'Shoulder\LT_01',
    r'J_Bip_\L_UpperArm',
    r'J_\L_UpArm',
    r'J_\L_Elbow',
    r'Arm_1_\L',
    r'Bip_UpperArm_\L',
    r'Upperarm01_\L',
    r'\L_Shldr',
    r'\LShldrBend',
    r'Arm_Stretch_\L',
    r'J_Ude_A_\L',
    r'J_Shoulder_\L',
    r'\LUpperArm',
    r'Bip_\L_Arm1',
]
bone_rename['Left arm'] = [
    '+_Leisure_Elder_Supplement',
]
bone_rename[r'\Left elbow'] = [
    r'\Left_Elbow',
    r'\LeftElbow',
    r'Elbow_\L',
    r'\L_Elbow',
    r'Mixamorig_\LeftForeArm',
    r'Arm_\Left_Elbow',
    r'Bip_\L_ForeArm',
    r'Bip_LowerArm_\L',
    r'B_\L_Arm2',
    r'Fore_Arm_\L',
    r'ForeArm_\L',
    r'\LForeArm',
    r'\L_ForeArm',
    r'\LeftLowArm',
    r'\Left_Forearm',
    r'\L_Foarm',
    r'Loarm_\L',
    r'\L_Arm_02',
    r'\LeftForeArm',
    r'\L_Forearm_1',
    r'Lower_Arm_\L',
    r'ElbowFor_Correction_\L',
    r'\L_ARM2',
    r'Arm\L2',
    r'\LArmJ',
    r'Elb_\L',
    r'Arm_\Left_Elbow_1',
    r'LowerArm_\L',
    r'\Lf_Elbow',
    r'Arm_Lower_\L',
    r'\Left_Forarm',
    r'\Larm2',
    r'Hand(\L)07',
    r'Lowarm_\L',
    r'\L_Hiji',
    r'Elbow\LT_01',
    r'J_Bip_\L_LowerArm',
    r'J_\L_ForeArm',
    r'Arm_2_\L',
    r'Bip_Forearm_\L',
    r'Lowerarm01_\L',
    r'\LElbow',
    r'\LForearmBend',
    r'Forearm_Stretch_\L',
    r'J_Ude_B_\L',
    r'J_Elbow_\L',
    r'\L_LowerArm',
    r'Bip_\L_Arm2',
]
bone_rename[r'\Left wrist'] = [
    r'\Left_Wrist',
    r'\LeftWrist',
    r'Wrist_\L',
    r'Wrist2_\L',
    r'HandAux2_\L',
    r'Mixamorig_\LeftHand',
    r'Arm_\Left_Wrist',
    r'Arm_\Left_Wirst',
    r'Bip_\L_Hand',
    r'Bip_Hand_\L',
    r'B_\L_Hand',
    r'Hand_\L',
    r'Hand\L',
    r'\LHand',
    r'\LHandN',
    r'\LeftHand',
    r'\Left_Hand',
    r'\L_Hand',
    r'\L_Hand_1',
    r'\LFingerBaseN',
    r'\Lf_Wrist',
    r'Palm_\L',
    r'Hand(\L)00',
    r'\L_Te',
    r'Hand\LT_01',
    r'J_Bip_\L_Hand',
    r'J_\L_Wrist',
    r'\L_Wrist',
    r'\LWrist',
    r'J_Te_\L',
    r'J_Wrist_\L',
]
bone_rename['Left wrist'] = [
    'Left_Hand_003',
]
bone_rename['Right wrist'] = [
    'Right_Hand_002',
]
bone_rename[r'\Left leg'] = [
    r'\Left_Leg',
    r'\Left_Foot',
    r'\LeftLeg',
    r'Hip.\L',
    r'Leg_\L',
    r'Leg_\L_001',
    r'Leg\L1',
    r'LegWAux_\L',
    r'Leg00003333_\L',
    r'Leg00004444_\L',
    r'Mixamorig_\LeftUpLeg',
    r'Leg_\Left_Thigh',
    r'Bip_\L_Thigh',
    r'Bip_Hip_\L',
    r'B_\L_Leg1',
    r'Upper_Leg_\L',
    r'\LThigh',
    r'Thigh_\L',
    r'\L_Thigh',
    r'\LeftUpLeg',
    r'\LeftHip',
    r'\Left_Thigh',
    r'Upleg_\L',
    r'\L_Hip',
    r'\L_Leg_01',
    r'\L_Femur',
    r'Waist_Cancel_\Left',
    r'Waist_Cancellation_\Left',
    r'\L_Femur_1',
    r'\L_LEG1',
    r'\LLegJ',
    r'Tg_\L',
    r'Leg_\Left_Thigh_1',
    r'UpperLeg_\L',
    r'\Lf_Leg',
    r'\L_UpLeg',
    r'Thigh00_\L',
    r'\Lfoot1',
    r'Leg(\L)04',
    r'\L_Momo',
    r'Leg_Thigh_\L',
    r'\L_Leg',
    r'Hip\LT_01',
    r'J_Bip_\L_UpperLeg',
    r'J_\L_UpLeg',
    r'Leg\L',
    r'Leg_1_\L',
    r'Bip_Thigh_\L',
    r'Groin_\L',
    r'Upperleg01_\L',
    r'\LThighBend',
    r'Thigh_Stretch_\L',
    r'J_Asi_A_\L',
    r'J_Hip_\L',
    r'\LUpLeg',
    r'\L_UpperLeg',
    r'Bip_\L_Leg',
]
bone_rename[r'\Left knee'] = [
    r'\Left_Knee',
    r'\LeftKnee',
    r'Knee_\L_001',
    r'Knee_\L',
    r'Mixamorig_\LeftLeg',
    r'Leg_\Left_Knee',
    r'Bip_\L_Calf',
    r'Bip_Knee_\L',
    r'B_\L_Leg2',
    r'Lower_Leg_\L',
    r'\LLeg',
    r'\LShin',
    r'Shin_\L',
    r'\L_Calf',
    r'Calf_\L',
    r'\LeftLowLeg',
    r'\Left_Shin',
    r'Loleg_\L',
    r'\L_Leg_02',
    r'\L_KneeLower',
    r'Tibia_\L',
    r'\L_Tibia',
    r'\L_Tibia_1',
    r'\L_LEG2',
    r'Leg\L2',
    r'\LKneeJ',
    r'\LKnee',
    r'LowerLeg_\L',
    r'\Lf_Knee',
    r'\L_Knee',
    r'Leg01_\L',
    r'\Lfoot2',
    r'Leg(\L)00',
    r'\L_Sune',
    r'Leg_Calf_\L',
    r'Knee\LT_01',
    r'J_Bip_\L_LowerLeg',
    r'J_\L_Leg',
    r'Knee\L',
    r'Leg_2_\L',
    r'Bip_Leg_\L',
    r'Lowerleg01_\L',
    r'Leg_Stretch_\L',
    r'J_Asi_B_\L',
    r'J_Knee_\L',
    r'\LCalf',
    r'\L_LowerLeg',
    r'Bip_\L_Leg1',
]
bone_rename[r'\Left ankle'] = [
    r'\Left_Ankle',
    r'\Left_Ankle_001',
    r'\LeftAnkle',
    r'Ankle_\L',
    r'\L_Ankle',
    r'Mixamorig_\LeftFoot',
    r'Leg_\Left_Ankle',
    r'Eg_\Left_Ankle',
    r'Bip_\L_Foot',
    r'Bip_Foot_\L',
    r'B_\L_Foot',
    'Lower',
    r'\LFoot',
    r'Foot_\L',
    r'Foot\L',
    r'\L_Foot',
    r'\LeftFoot',
    r'Leg_\Left_Foot',
    r'\L_Foot_01',
    r'LegIK_\L',
    r'\L_Foot_1',
    r'\L_FOOT1',
    r'\LFootJ',
    r'\Lf_Ankle',
    r'\Left_Heel',
    r'Leg(\L)02',
    r'\L_Asi',
    r'Foot\LT_01',
    r'J_Bip_\L_Foot',
    r'J_\L_Foot',
    r'\LAnkle',
    r'J_Asi_D_\L',
    r'J_Ankle_\L',
    r'\LFoot',
]
bone_rename[r'\Left toe'] = [
    r'\Left_Toe',
    r'\Left_Toes',
    r'\LeftToe',
    r'\LeftToe1',
    r'LegTip_\L',
    r'LegTipEX_\L',
    r'ClawTipEX_\L',
    r'Mixamorig_\LeftToeBase',
    r'Leg_\Left_Toes',
    r'Bip_\L_Toe0',
    r'B_\L_Toe',
    r'\LToe',
    r'Toe_\L',
    r'Toe\L',
    r'\L_Toe',
    r'\L_Toe1',
    r'\L_Toe2',
    r'\LeftToeBase',
    r'Toe1_1_\L',
    r'Leg_\Left_Foot_Toes',
    r'ToeSaki_\L',
    r'\L_Toes',
    r'\L_Toe0',
    r'\L_Toe_1',
    r'\L_FOOT2',
    r'\LToeN',
    r'\LToeA',
    r'Toes_\L',
    r'ToeTip_\L',
    r'ToeTip2_\L',
    r'\Lf_Toe',
    r'Tsumasaki_\L',
    r'Leg_\Left_Toe',
    r'Leg(\L)03',
    r'Toe\LT_01',
    r'J_Bip_\L_ToeBase',
    r'J_\L_Toe',
    r'Bip_Toe_\L',
    r'Toe_Boot_\L',
    r'Toes_01_\L',
    r'J_Asi_E_\L',
    r'J_Ball_\L',
    r'\LToeBase',
    r'\LToe0',
]
bone_rename[r'Eye_\L'] = [
    r'\Left_Eye',
    r'Mixamorig_\LeftEye',
    r'Head_Eyeball_\Left',
    r'Head_Eyeball_\Left_1',
    r'FEye\L',
    r'Eye\L',
    r'\L_Eye',
    r'Bip_Eyeball_\L',
    r'G_Eye_\L',
    r'Eyes\L',
    r'\Lf_Eye',
    r'Eyes(\L)',
    r'Eye\LT_01',
    r'J_Adj_\L_FaceEye',
    r'Bip_Eye_\L',
    r'\LEye',
    r'J_F_Eye_\L',
]
bone_rename['Eye_L'] = [
    'Eyes',
]
bone_rename['Eye_R'] = [
    'HL',
]
bone_rename[r'Breast_\L'] = [
    r'J_Sec_\L_Bust1',
    r'\LPectoral',
    r'Spine_\Left_Breast_2',
    r'Breast_Def_\L',
]

################################
# Capitalize all bone names!
# Capitalize after each underscore!
# Replace '-' with '_'
# Replace ' ' with '_'
# Replace 'ValveBiped_' with ''
# Replace 'Bip1_' with 'Bip_'
# Replace 'Bip01_' with 'Bip_'
# Replace 'Bip001_' with 'Bip_'
# Replace '_Bone' with ''
#
# Replace New Bone Patterns:
#   Left/Right = \Left
#   L/R = \L
# Replace Old Bone Patterns:
#   Left/Right = \Left
#   left/right = \left
#   L/R = \L
#   l/r = \l
################################
bone_reweight = OrderedDict()
bone_reweight['Hips'] = [
    'LowerBody1',
    'Lowerbody2',
    'Pelvis_Adj',
    'Left_Hip',
    'Right_Hip',
    'Feet',
    'Waist02_001',
    'Bip_SpineBase',
    'Bip_HipFront_L',
    'Bip_HipFront_R',
    'Root_Pelvis_2',
    'Root_Waist',
    'Root_Waist_L',
    'Root_Waist_R',
    'Hiphalf_L',
    'Hiphalf_R',
    'PelvisDown_Sld',
]
bone_reweight['Spine'] = [
    'UpperBodyx',
    'Spine_Lower_Adj',
    'Spine_Middle_Adj',
    'Bip_Spine0a',
]
bone_reweight['Chest'] = [
    # 'UpperBodyx2',
    # 'J_Bip_C_UpperChest',
    'Bip_Spine1a',
    'Bip_CollarHelper_L',
    'Bip_CollarHelper_R',
]
bone_reweight['Upper Chest'] = [
    'J_Adj_C_UpperChest',
    'Spine_Upper_Adj',
]
bone_reweight['Neck'] = [
    'Neck1',
    'Neck2',
    'Neckx',
    'NeckW',
    'NeckW2',
    'Neck01',
    'Neck02',
    'Neck03',
    'J_Neck2',
    'NeckUpper',
]
bone_reweight['Head'] = [
    'Neckx2',
    'Head_001',
    'J_Adj_L_FaceEyeSet',
    'J_Adj_R_FaceEyeSet',
]
bone_reweight[r'\Left shoulder'] = [
    r'ShoulderP_\L',
    r'Shoulder1_\L',
    r'Shoulder2_\L',
    r'Shoulder3_\L',
    r'Shoulder4_\L',
    r'ShoulderSleeve_\L',
    r'SleeveShoulderIK_\L',
    r'\Left_Shoulder_Weight',
    r'ShoulderS_\L',
    r'ShoulderW_\L',
    r'B_\L_ArmorParts',
    r'Bip_\L_Shoulder',
    r'Kata_\L',
    r'Bip_\L_Clavicle_Rig',
    r'Shoulder02_\L',
    r'Shoulder1_WayA_\L',
    r'Shoulder\LT_Roll_01',
    r'Bip_Armpit_\L',
    r'Bip_UpperArmBase_\L',
    r'ShoulderHalf_\L',
    r'ShoulderAux_\L',
]
bone_reweight[r'\Left arm'] = [
    r'Arm01_\L',
    r'Arm02_\L',
    r'Arm03_\L',
    r'Arm04_\L',
    r'Arm05_\L',
    r'ArmTwist0_\L',
    r'ArmTwist1_\L',
    r'ArmTwist2_\L',
    r'ArmTwist3_\L',
    r'ArmTwist4_\L',
    r'ArmTwist5_\L',
    r'ArmTwist5_\L_001',
    r'ArmTwist+0_\L',
    r'ArmTwist+1_\L',
    r'ArmTwist+2_\L',
    r'ArmTwist+3_\L',
    r'ArmTwist+4_\L',
    r'ArmTwist+5_\L',
    r'\Left_Arm_Twist',
    r'\Left_Arm_Torsion',
    r'\Left_Arm_Torsion_1',
    r'\Left_Arm_Tight',
    r'\Left_Arm_Tight_1',
    r'\Left_Arm_Tight_2',
    r'\Left_Arm_Tight_3',
    r'\Left_Upper_Arm_Twist',
    r'\Left_Upper_Arm_Twist_B',
    r'ElbowAux_\L',
    r'ElbowAux+_\L',
    r'+ElbowAux_\L',
    r'ArmSleeve_\L',
    r'Arm_Sleeve_\L',
    r'ArmTwist_Sleeve_\L',
    r'ShoulderTwist_\L',
    r'ArmW_\L',
    r'ArmW2_\L',
    r'SleeveArm_\L',
    r'SleeveElbowAux_\L',
    r'ArmxcIa_\L',
    r'ArmRotation_\L',
    r'ArmTwistReturn_\L',
    r'DEF_Upper_Arm_02_\L',
    r'DEF_Upper_Arm_Twist_25_\L',
    r'DEF_Upper_Arm_Twist_50_\L',
    r'DEF_Upper_Arm_Twist_75_\L',
    r'Arm_\Left_Bicep',
    r'\LArmB',
    r'\L_Sub_Shoulder',
    r'X_\L_ArmZoom1',
    r'X_\L_ArmZoom2',
    r'X_\L_ArmZoom3',
    r'X_\L_ArmZoom4',
    r'X_\L_ArmZoom5',
    r'B_\L_Elbow',
    r'B_\L_ArmHelper',
    r'B_\L_UpperArm_Hojo01',
    r'B_\L_Hiji01',
    r'Bip_\L_Trapezius',
    r'Bip_\L_Bicep',
    r'Arm_\Left_Elbow_Ctr',
    r'Arm_\Left_Shoulder_Ctr_1',
    r'\L_Sho_Ast',
    r'\L_Arm_Ast',
    r'Uppertwist1_\L',
    r'Arm_\Left_Shoulder_2_Ctr',
    r'Arm_\Left_Shoulder_2_Ctr2',
    r'ArmS_\L',
    r'Arm\L1Sub',
    r'\LSholJb',
    r'\LUpArmTwistjb',
    r'Bone_Adjustment_\Left_Arm',
    r'\LeftArmRoll',
    r'\LeftArmBend',
    r'\L_Uptwist_A',
    r'\L_Uptwist_B',
    r'Shoulder5_\L',
    r'Shoulder6_\L',
    r'Shoulder7_\L',
    r'ElbowUpper_\L',
    r'Arm_\Left_Sh_Tw',
    r'Arm_\Left_Shoulder_Ctrl_1',
    r'Arm_\Left_Shoulder_Ctrl_2',
    r'Bip_\L_UpperArm_Rig',
    r'Bip_\L_UpperArm_Twist',
    r'Arm_WayA_\L',
    r'\L_Arm_EX',
    r'\L_Elbow_EX',
    r'Arm1D_\L',
    r'Arm2D_\L',
    r'Bip_UpperArmTwistTop_\L',
    r'Bip_ArmpitRingBase_\L',
    r'Bip_UpperArmTwistBottom_\L',
    r'Bip_ForearmHelper_\L',
    r'Bip_ElbowHelper_\L',
    r'Hlp_UpperArm_\L',
    r'Upperarm02_\L',
    r'\LArmJiggle',
    r'\LArmJiggle2',
    r'\LArmJiggle3',
    r'\LShldrTwist',
    r'J_Sec_\L_UpperArm',
    r'UpArmLow_\L',
    r'UpArmUp_\L',
    r'N_Hkata_\L',
    r'Arm_\Left_Shoulder_Tw_A',
    r'Arm_\Left_Shoulder_Tw_B',
    r'ArmAux_\L',
]
bone_reweight['Left arm'] = [  # This has apparently no side in the name
    'エプロンArm',
]
bone_reweight[r'\Left elbow'] = [
    r'Elbow1_\L',
    r'Elbow2_\L',
    r'Elbow3_\L',
    r'Elbow+1_\L',
    r'Elbow+2_\L',
    r'Elbow+3_\L',
    r'Elbow01_\L',
    r'Elbow02_\L',
    r'Elbow03_\L',
    r'Elbow04_\L',
    r'Elbow05_\L',
    r'HandTwist_\L',
    r'HandTwist1_\L',
    r'HandTwist2_\L',
    r'HandTwist3_\L',
    r'HandTwist4_\L',
    r'HandTwist5_\L',
    r'HandTwist5_\L_001',
    r'HandTwist+1_\L',
    r'HandTwist+2_\L',
    r'HandTwist+3_\L',
    r'HandTwist+4_\L',
    r'HandTwist+5_\L',
    r'HandTwist+6_\L',
    r'HandTwist+7_\L',
    r'\Left_Hand_1',
    r'\Left_Hand_2',
    r'\Left_Hand_3',
    r'\Left_Hand_Twist',
    r'\Left_Hand_Twist_1',
    r'\Left_Hand_Twist_2',
    r'\Left_Hand_Thread_3',
    r'ElbowSleeve_\L',
    r'WristAux_\L',
    r'ElbowTwist_\L',
    r'ElbowTwist2_\L',
    r'ElbowW_\L',
    r'ElbowW2_\L',
    r'SleeveElbow_\L',
    r'Elbow_Sleeve_\L',
    r'SleeveMouth_\L',
    r'ElbowRotation_\L',
    r'HandTwistRotation1_\L',
    r'HandTwistRotation2_\L',
    r'DEF_Upper_Arm_Elbow_\L',
    r'DEF_Forearm_Twist_25_\L',
    r'DEF_Forearm_Twist_50_\L',
    r'DEF_Forearm_Twist_75_\L',
    r'+Elbow_\L',
    r'Elbowa_\L',
    r'Arm_\Left_Wrist_Adj',
    r'Arm_\Left_Forearm',
    r'\Left_Forearm_Twist',
    r'\LHandEX',
    r'\L_Sub_Elbow',
    r'X_\L_ArmZoom6',
    r'X_\L_ArmZoom7',
    r'X_\L_ArmZoom8',
    r'X_\L_ArmZoom9',
    r'X_\L_ArmZoom10',
    r'B_\L_ArmRoll',
    r'Bip_\L_ForeTwist',
    r'Bip_\L_ForeTwist1',
    r'Bip_\L_Elbow',
    r'Bip_\L_Ulna',
    r'Bip_\L_Wrist',
    r'Arm_\Left_Wrist_Ctr',
    r'\L_Elb_Ast',
    r'\L_Wrist_Ast',
    r'Foretwist_\L',
    r'Foretwist1_\L',
    r'Arm_\Left_Elbow_Ctr2',
    r'ElbowS_\L',
    r'Arm\L2Sub',
    r'\LTekubiJb',
    r'\LArmTwistjb',
    r'\LElbowJb',
    r'\LForeArmSub',
    r'TW_Elb_\L',
    r'\LeftElbowRoll',
    r'\LeftForeArmRoll',
    r'\LeftForeArmRoll1',
    r'\LeftForeArmRoll2',
    r'ElbowMiddle_\L',
    r'ElbowLower1_\L',
    r'ElbowLower2_\L',
    r'Arm_\Left_Elbow_Ctrl',
    r'Arm_\Left_Wrist_Ctrl_1',
    r'Arm_\Left_Wrist_Ctrl_2',
    r'Bip_\L_Forearm_Rig',
    r'Bip_\L_Forearm_Twist',
    r'\L_Tekubi',
    r'Forearm02_\L',
    r'Wrist_\L_001',
    r'Cf_D_Hand_\L',
    r'Elbo_\L',
    r'Forearm01_\L',
    r'Elboback_\L',
    r'\L_Wrist_EX',
    r'HandHelperBone_\L',
    r'BK_\L_Elbow_00',
    r'BK_\L_Elbow_01',
    r'BK_\L_Elbow_02',
    r'BK_\L_Elbow_03',
    r'BK_\L_Elbow_04',
    r'Wrist\LT_Roll_01',
    r'ForArm\LT_Roll_01',
    r'Arm_\Left_Forearm_Adj_1',
    r'H_Elbow\L',
    r'Bip_ForearmTwistTop_\L',
    r'Bip_ForearmTwistMiddle_\L',
    r'Bip_ForearmTwistBottom_\L',
    r'Bip_ElbowFront_\L',
    r'Bip_ElbowBackTop_\L',
    r'Bip_ElbowBack_\L',
    r'Bip_WristTwistBase_\L',
    r'Bip_WristTwistOut_\L',
    r'Bip_WristTwistN_\L',
    r'Bip_WristTwistIn_\L',
    r'Bip_WristTwistS_\L',
    r'Hlp_Wrist_\L',
    r'Hlp_LowerArm_\L',
    r'Lowerarm02_\L',
    r'\LElbowJiggle',
    r'\LForearmJiggle1',
    r'\LForearmJiggle2',
    r'\LCuffsMain',
    r'\LForearmTwist',
    r'J_Sec_\L_LowerArm',
    r'ForearmLow_\L',
    r'ForearmUp_\L',
    r'N_Hhiji_\L',
    r'N_Hte_\L',
    r'Arm_\Left_Wrist_Tw_E',
    r'ElbowAux_\L',
]
bone_reweight[r'\Left wrist'] = [
    # 'Sleeve3_\L',
    r'WristSleeve_\L',
    r'WristW_\L',
    r'WristS_\L',
    r'IndexFinger0_\L',
    r'MiddleFinger0_\L',
    r'RingFinger0_\L',
    r'LittleFinger0_\L',
    r'DEF_Hand_\L',
    r'DEF_Halm_01_\L',
    r'DEF_Halm_02_\L',
    r'DEF_Halm_03_\L',
    r'DEF_Halm_04_\L',
    r'Arm_\Left_Hand',
    r'\LIndexN',
    r'\LMiddleN',
    r'\LRingN',
    r'\LPinkyN',
    r'\LHandSub',
    r'\LeftHandIndex0',
    r'\LeftHandMiddle0',
    r'\LeftHandRing0',
    r'\LeftHandPinky0',
    r'\Lf_Metacarpal',
    r'\Left_Hand_001',
    r'\Left_Hand_005',
    r'Unusedopt_Hand_*_Metacarpal04_1_\L',
    r'\L_Finger_Ctr',
    r'Bip_\L_Carpal1',
    r'Bip_\L_Carpal2',
    r'Bip_\L_Carpal3',
    r'Bip_\L_Carpal4',
    r'Offset_Hand_\L',
    r'\L_FingerBase',
    r'BK_\L_Hand_00',
    r'BK_\L_Hand_01',
    r'BK_\L_Hand_02',
    r'BK_\L_Hand_03',
    r'BK_\L_Hand_04',
    r'Arm_\Left_Finger_5_Base',
    r'\Left_Finger_Index_Metacarpal',
    r'\Left_Finger_Ring_Metacarpal',
    r'Metacarpal1_\L',
    r'Metacarpal2_\L',
    r'Metacarpal3_\L',
    r'Metacarpal4_\L',
    r'\LCarpal1',
    r'\LCarpal2',
    r'\LCarpal3',
    r'\LCarpal4',
    r'Arm_\Left_Fist',
    r'J_Pinkybase_\L',
    r'J_Ringbase_\L',
]
bone_reweight['Left wrist'] = [
    'Left_Hand_002',
    'Left_Hand_006',
]
bone_reweight['Right wrist'] = [
    'Right_Hand_003',
    'Right_Hand_004',
]
bone_reweight[r'\Left leg'] = [
    r'LegD_\L',
    r'LegD_001_\L',
    r'+LegD_\L',
    r'\Left_Foot_D',
    r'\Left_Foot_Complement',
    r'\Left_Foot_Supplement',
    r'LegcntEven_\L',
    r'\LLegTwist1',
    r'\LLegTwist2',
    r'\LLegTwist3',
    r'\Left_Leg_Twist',
    r'LegW_\L',
    r'LegW2_\L',
    r'LowerKnee_\L',
    r'UpperKnee_\L',
    r'LegX1_\L',
    r'LegX2_\L',
    r'LegX3_\L',
    r'\Left_Knee_EX',
    r'\Left_Foot_EX',
    r'KneeEX_\L',
    r'LegEX_\L',
    r'Thigh_\L',
    r'Leg+_\L',
    r'Leg++_\L',
    r'Leg+++_\L',
    r'Leg++++_\L',
    r'Knee++_\L',
    r'Peaches_\L',
    r'Pants_Stuff_000_\L',
    r'Pants_Stuff_001_\L',
    r'DEF_Thigh_Sub_\L',
    r'DEF_Thigh_01_\L',
    r'DEF_Thigh_02_\L',
    r'DEF_Thigh_Twist_25_\L',
    r'DEF_Thigh_Twist_50_\L',
    r'DEF_Thigh_Twist_75_\L',
    r'Leg_\Left_Thigh_Adj_1',
    r'Leg_\Left_Thigh_Adj_2',
    r'Leg_\Left_Thigh_Adj_3',
    r'B_\L_LegHelper',
    r'B_\L_Knee',
    r'Leg_\Left_Thigh_Ctr',
    r'Leg_\Left_Thigh_Ctrl_1',
    r'Leg_\Left_Thigh_Ctrl_2',
    r'Leg_\Left_Thigh_Ctrl_3',
    r'Leg_\Left_Knee_Ctr',
    r'B_\L_Hiza01',
    r'B_\L_Pelvis_Hojo01',
    r'Bip_\L_ThighTwist',
    r'Bip_\L_ThighTwist1',
    r'\L_KneeUpper',
    r'\L_Tro_Ast',
    r'Momotwist_\L',
    r'Momotwist2_\L',
    r'Momoniku_\L',
    r'+_\Left_Foot_D',
    r'Leg_\Left_Thigh_Ctr2',
    r'LegDS_\L',
    r'\Left_Leg_2',
    r'\Left leg 2',
    r'LegD_001_\L',
    r'\LComaneciJb',
    r'\LeftHipsRoll',
    r'\LeftUpLegRoll',
    r'\LeftKneeUp',
    r'Peaches1_\L',
    r'Peaches1_2_\L',
    r'Peaches2_\L',
    r'Peaches2_2_\L',
    r'Peaches3_\L',
    r'Peaches3_2_\L',
    r'Peaches4_\L',
    r'Peaches4_2_\L',
    r'Peaches5_\L',
    r'Peaches5_2_\L',
    r'Peaches6_\L',
    r'Peaches7_\L',
    r'Peaches8_\L',
    r'Peaches9_\L',
    r'Peaches10_\L',
    r'Bip_\L_Thigh_Rig',
    r'Leg(\L)_0',
    r'Thigh01_\L',
    r'Thigh02_\L',
    r'Thigh03_\L',
    r'\L_Leg_EX',
    r'\L_Knee_EX',
    r'Knee\LT_Roll_01',
    r'Hip\LT_Roll_01',
    r'Leg_\Left_Hip_Adj',
    r'Leg_\Left_Knee_Adj',
    r'Leg_\Left_Thigh_Adj',
    r'Bip_ThighTwistTop_\L',
    r'Bip_ThighTwistBottom_\L',
    r'Bip_KneeIn_\L',
    r'Bip_KneeOut_\L',
    r'Hlp_Hip_\L',
    r'Upperleg02_\L',
    r'\LThighTwist',
    r'J_Sec_\L_UpperLeg',
    r'\Left_Thigh_Twist',
    r'ThighLow_\L',
    r'ThighUp_\L',
    r'LegAux_\L',
]
bone_reweight[r'\Left knee'] = [
    r'KneeD_\L',
    r'KneeD_001_\L',
    r'\Left_Knee_D',
    r'KneecntEven_\L',
    r'\LTibiaTwist1',
    r'\LTibiaTwist2',
    r'\LTibiaTwist3',
    r'KneeW1_\L',
    r'KneeW2_\L',
    r'Knee+_\L',
    r'Knee+++_\L',
    r'Knee++++_\L',
    r'Ankle++_\L',
    r'KneeArmor2_\L',
    r'KneeX1_\L',
    r'KneeX2_\L',
    r'KneeX3_\L',
    r'Leg_\Left_Acc',
    r'\Left_Knee_Twist',
    r'\Left_Ankle_EX',
    r'AnkleEX_\L',
    r'KneeAux_\L',
    r'Shin_\L',
    r'DEF_Knee_\L',
    r'DEF_Knee_02_\L',
    r'DEF_Shin_01_\L',
    r'DEF_Shin_02_\L',
    r'DEF_Shin_Twist_25_\L',
    r'DEF_Shin_Twist_50_\L',
    r'DEF_Shin_Twist_75_\L',
    r'Leg_\Left_Ankle_Adj',
    r'\L_Knee_Ast',
    r'\L_HorseLink',
    r'KneeD2_\L',
    r'\LeftKneeRoll',
    r'\LeftKneeLow',
    r'Leg_\Left_Knee_Ctrl',
    r'Bip_\L_Calf_Rig',
    r'Leg(\L)01',
    r'Cf_D_KneeF_\L',
    r'Leg02_\L',
    r'Leg03_\L',
    r'KneeB_\L',
    r'\L_Ankle_EX',
    r'BK_\L_Knee_00',
    r'BK_\L_Knee_01',
    r'BK_\L_Knee_02',
    r'BK_\L_Knee_03',
    r'BK_\L_Knee_04',
    r'Foot\LT_Roll_01',
    r'J_\L_Knee',
    r'Bip_LegTwistTop_\L',
    r'Bip_LegTwistBottom_\L',
    r'Bip_KneeTwistTopOut_\L',
    r'Bip_KneeTwistBottomOut_\L',
    r'Bip_KneeTwistBottomIn_\L',
    r'Bip_Ankle_\L',
    r'Bip_AnkleHelper_\L',
    r'Hlp_Knee_\L',
    r'Hlp_Foot_\L',
    r'KneeUpper_\L',
    r'KneeLower_\L',
    r'Lowerleg02_\L',
    r'\LKneeJiggle',
    r'J_Sec_\L_LowerLeg',
    r'\Left_Ankle_Twist',
    r'CalfLow_\L',
    r'CalfUp_\L',
    r'J_Asi_C_\L',
]
bone_reweight[r'\Left ankle'] = [
    r'AnkleD_\L',
    r'\Left_Ankle_D',
    r'AnkleEven_\L',
    r'AnkleW1_\L',
    r'AnkleW2_\L',
    r'ToeTipMovable_\L',
    r'AnkleArmor_\L',
    r'LowerUseless_\L',
    r'Ankle+_\L',
    r'Ankle+++_\L',
    r'Ankle++++_\L',
    r'DEF_Foot_\L',
    'LegA_L',
    r'Bip_\L_Foot',
    r'Foot_Controller_\L',
    r'AnkleD_001_\L',
    r'Bip_\L_Foot_Rig',
    r'BK_\L_Ankle_00',
    r'BK_\L_Ankle_01',
    r'BK_\L_Ankle_02',
    r'BK_\L_Ankle_03',
    r'BK_\L_Ankle_04',
    r'Foot_\LT_01_IK',
    r'\LMetatarsals',
    r'Leg_\Left_Ankle_Heel',
]
bone_reweight[r'\Left toe'] = [
    r'\Left_Toes',
    r'ClawTipEX_\L',
    r'ClawTipEX2_\L',
    r'ClawTipThumbEX_\L',
    r'ClawTipThumbEX2_\L',
    r'\Left_Toe_EX',
    r'\Left_Foot_Tip_EX',
    r'LegTip2_\L',
    r'DEF_Toe_\L',
    r'Bip_\L_Toe01',
    r'Bip_\L_Toe1',
    r'Bip_\L_Toe11',
    r'Bip_\L_Toe2',
    r'Bip_\L_Toe21',
]
bone_reweight[r'Eye_\L'] = [
    r'EyeW_\L',
    r'EyeLight_\L',
    r'EyeLight1_\L',
    r'EyeLight2_\L',
    r'EyeLight3_\L',
    r'EyeLight4_\L',
    r'EyeReturn_\L',
    r'\Left_Eye_Return',
    r'Pupil_\L',
    r'\Left_Pupil',
    r'\Left_Eye_Glint',
    r'Highlight_\L',
    r'F_EyeTip_\L',
    r'F_EyeLight1_\L',
    r'F_EyeLight2_\L',
    r'F_EyeLight3_\L',
    r'DEF_Eye_\L',
    r'EyeLight+_\L',
    r'EyeRotationErase_\L',
    r'EyeFlip_\L',
    r'\LeftEyeHighlight',
]
bone_reweight[r'Breast_\L'] = [
    r'DEF_Bust_01_\L',
    r'DEF_Bust_02_\L',
]

# Secondary reweight list.
bone_list_weight = {
    # Other model fixes
    'DEF_Zipper': 'Zipper',
    'B_F_Mune01': 'Breasts',
    'Bone': 'Pelwas_001',

    # Finger fixing
    # Left
    'DEF_Thumb_01_L_01': 'Thumb0_L',
    'DEF_Thumb_01_L_02': 'Thumb0_L',
    'DEF_Thumb_02_L': 'Thumb1_L',
    'DEF_Thumb_03_L': 'Thumb2_L',

    'DEF_F_Index_01_L_01': 'IndexFinger1_L',
    'DEF_F_Index_01_L_02': 'IndexFinger1_L',
    'DEF_F_Index_02_L': 'IndexFinger2_L',
    'DEF_F_Index_03_L': 'IndexFinger3_L',

    'DEF_F_Middle_01_L_01': 'MiddleFinger1_L',
    'DEF_F_Middle_01_L_02': 'MiddleFinger1_L',
    'DEF_F_Middle_02_L': 'MiddleFinger2_L',
    'DEF_F_Middle_03_L': 'MiddleFinger3_L',

    'DEF_F_Ring_01_L_01': 'RingFinger1_L',
    'DEF_F_Ring_01_L_02': 'RingFinger1_L',
    'DEF_F_Ring_02_L': 'RingFinger2_L',
    'DEF_F_Ring_03_L': 'RingFinger3_L',

    'DEF_F_Pinky_01_L_01': 'LittleFinger1_L',
    'DEF_F_Pinky_01_L_02': 'LittleFinger1_L',
    'DEF_F_Pinky_02_L': 'LittleFinger2_L',
    'DEF_F_Pinky_03_L': 'LittleFinger3_L',

    # Right
    'DEF_Thumb_01_R_01': 'Thumb0_R',
    'DEF_Thumb_01_R_02': 'Thumb0_R',
    'DEF_Thumb_02_R': 'Thumb1_R',
    'DEF_Thumb_03_R': 'Thumb2_R',

    'DEF_F_Index_01_R_01': 'IndexFinger1_R',
    'DEF_F_Index_01_R_02': 'IndexFinger1_R',
    'DEF_F_Index_02_R': 'IndexFinger2_R',
    'DEF_F_Index_03_R': 'IndexFinger3_R',

    'DEF_F_Middle_01_R_01': 'MiddleFinger1_R',
    'DEF_F_Middle_01_R_02': 'MiddleFinger1_R',
    'DEF_F_Middle_02_R': 'MiddleFinger2_R',
    'DEF_F_Middle_03_R': 'MiddleFinger3_R',

    'DEF_F_Ring_01_R_01': 'RingFinger1_R',
    'DEF_F_Ring_01_R_02': 'RingFinger1_R',
    'DEF_F_Ring_02_R': 'RingFinger2_R',
    'DEF_F_Ring_03_R': 'RingFinger3_R',

    'DEF_F_Pinky_01_R_01': 'LittleFinger1_R',
    'DEF_F_Pinky_01_R_02': 'LittleFinger1_R',
    'DEF_F_Pinky_02_R': 'LittleFinger2_R',
    'DEF_F_Pinky_03_R': 'LittleFinger3_R',
}

bone_rename_fingers = OrderedDict()
bone_rename_fingers[r'Thumb0_\L'] = [
    # 'Arm_\Left_Finger_1a',
    r'T_1_\L',
    r'\LThumb1',
    r'\LThumb1N',
    r'Thumb_01_\L',
    r'\L_Thumb0',
    r'\L_Thumb_01',
    r'\LeftHandThumb1',
    r'\LeftFinger0',
    r'Finger1_2_\L',
    r'H_\L_Thumb1',
    r'Bip_Thumb_0_\L',
    r'Bip_\L_Finger0',
    r'\L_Fing1_A',
    r'\L_Thumb_A',
    r'\L_Thumb_A_1',
    r'T1_\L',
    'L_FINGER11',
    r'\Leftthumb1',
    r'Thumb1\L',
    r'ThmbA_\L',
    r'\Lf_Thumb1',
    r'\L_Finger_A1',
    r'Thumb01_\L',
    r'Arm_\Left_Finger_1_1',
    r'\L_Thumbfinger_A',
    r'ThumbA\LT_01',
    r'J_Bip_\L_Thumb1',
    r'Bip_FThumb01_\L',
    r'Arm_\Left_Finger_1a',
    r'J_Oya_A_\L',
    r'J_Thumb_\L_1',
    r'\LHandThumb',
    r'\LFinger0',
]
bone_rename_fingers[r'Thumb1_\L'] = [
    # 'Arm_\Left_Finger_1b',
    r'T_2_\L',
    r'\LThumb2',
    r'\LThumb2N',
    r'Thumb_02_\L',
    r'\L_Thumb1',
    r'\L_Thumb_02',
    r'\LeftHandThumb2',
    r'\LeftFinger01',
    r'Finger1_3_\L',
    r'H_\L_Thumb2',
    r'Bip_Thumb_1_\L',
    r'Bip_\L_Finger01',
    r'\L_Fing1_B',
    r'\L_Thumb_B',
    r'\L_Thumb_B_1',
    r'T2_\L',
    'L_FINGER12',
    r'\Leftthumb2',
    r'Thumb2\L',
    r'ThmbB_\L',
    r'\Lf_Thumb2',
    r'\L_Finger_A2',
    r'Thumb02_\L',
    r'Arm_\Left_Finger_1_2',
    r'\L_Thumbfinger_B',
    r'ThumbB\LT_01',
    r'J_Bip_\L_Thumb2',
    r'Bip_FThumb02_\L',
    r'Arm_\Left_Finger_1b',
    r'J_Oya_B_\L',
    r'J_Thumb_\L_2',
    r'\LHandThumb1',
    r'\LFinger01',
]
bone_rename_fingers[r'Thumb2_\L'] = [
    # 'Arm_\Left_Finger_1c',
    r'T_3_\L',
    r'\LThumb3',
    r'\LThumb3N',
    r'Thumb_03_\L',
    r'\L_Thumb2',
    r'\L_Thumb_03',
    r'\LeftHandThumb3',
    r'\LeftFinger02',
    r'Finger1_4_\L',
    r'H_\L_Thumb3',
    r'Bip_Thumb_2_\L',
    r'Bip_\L_Finger02',
    r'\L_Fing1_C',
    r'\L_Thumb_C',
    r'\L_Thumb_C_1',
    r'T3_\L',
    'L_FINGER13',
    r'Thumb3\L',
    r'ThmbC_\L',
    r'\Lf_Thumb3',
    r'\L_Finger_A3',
    r'Thumb03_\L',
    r'Arm_\Left_Finger_1_3',
    r'\L_Thumbfinger_C',
    r'ThumbC\LT_01',
    r'J_Bip_\L_Thumb3',
    r'Bip_FThumb03_\L',
    r'Arm_\Left_Finger_1c',
    r'J_Oya_C_\L',
    r'J_Thumb_\L_3',
    r'\LHandThumb2',
    r'\LFinger02',
]
bone_rename_fingers[r'IndexFinger1_\L'] = [
    r'Fore1_\L',
    r'I_1_\L',
    # 'Arm_\Left_Finger_2a',
    r'\LIndex1',
    r'\LIndex1N',
    r'F_Index_01_\L',
    r'\L_Index0',
    r'\L_Index_01',
    r'\LeftHandIndex1',
    r'\LeftFinger1',
    r'Finger2_2_\L',
    r'H_\L_Index1',
    r'Bip_Index_0_\L',
    r'Bip_\L_Finger1',
    r'\L_Fing2_A',
    r'\L_Index_A',
    r'\L_Index_A_1',
    r'If1_\L',
    'L_FINGER21',
    r'IndexFinger1\L',
    r'\LFingerD1',
    r'IndeA_\L',
    r'Index1_\L',
    r'\Lf_Index1',
    r'\L_Finger_B1',
    r'Index01_\L',
    r'Arm_\Left_Finger_2_1',
    r'\L_Indexfinger_A',
    r'IndexA\LT_01',
    r'J_Bip_\L_Index1',
    r'Bip_FIndex00_\L',
    r'Arm_\Left_Finger_2a',
    r'J_Hito_A_\L',
    r'J_Index_\L_1',
    r'\LHandIndex',
    r'\LFinger1',
]
bone_rename_fingers[r'IndexFinger2_\L'] = [
    r'Fore2_\L',
    r'I_2_\L',
    # 'Arm_\Left_Finger_2b',
    r'\LIndex2',
    r'\LIndex2N',
    r'F_Index_02_\L',
    r'\L_Index1',
    r'\L_Index_02',
    r'\LeftHandIndex2',
    r'\LeftFinger11',
    r'Finger2_3_\L',
    r'H_\L_Index2',
    r'Bip_Index_1_\L',
    r'Bip_\L_Finger11',
    r'\L_Fing2_B',
    r'\L_Index_B',
    r'\L_Index_B_1',
    r'If2_\L',
    'L_FINGER22',
    r'IndexFinger2\L',
    r'\LFingerD2',
    r'IndeB_\L',
    r'Index2_\L',
    r'\Lf_Index2',
    r'Index_02_\L',
    r'\L_Finger_B2',
    r'Arm_\Left_Finger_2_2',
    r'\L_Indexfinger_B',
    r'IndexB\LT_01',
    r'J_Bip_\L_Index2',
    r'Bip_FIndex01_\L',
    r'Arm_\Left_Finger_2b',
    r'J_Hito_B_\L',
    r'J_Index_\L_2',
    r'\LHandIndex1',
    r'\LFinger11',
]
bone_rename_fingers[r'IndexFinger3_\L'] = [
    r'Fore3_\L',
    r'I_3_\L',
    # 'Arm_\Left_Finger_2c',
    r'\LIndex3',
    r'\LIndex3N',
    r'F_Index_03_\L',
    r'\L_Index2',
    r'\L_Index_03',
    r'\LeftHandIndex3',
    r'\LeftFinger12',
    r'Finger2_4_\L',
    r'H_\L_Index3',
    r'Bip_Index_2_\L',
    r'Bip_\L_Finger12',
    r'\L_Fing2_C',
    r'\L_Index_C',
    r'\L_Index_C_1',
    r'If3_\L',
    'L_FINGER23',
    r'IndexFinger3\L',
    r'\LFingerD3',
    r'IndeC_\L',
    r'Index3_\L',
    r'\Lf_Index3',
    r'Index_03_\L',
    r'\L_Finger_B3',
    r'Index03_\L',
    r'Arm_\Left_Finger_2_3',
    r'\L_Indexfinger_C',
    r'IndexC\LT_01',
    r'J_Bip_\L_Index3',
    r'Bip_FIndex02_\L',
    r'Arm_\Left_Finger_2c',
    r'J_Hito_C_\L',
    r'J_Index_\L_3',
    r'\LHandIndex2',
    r'\LFinger12',
]
bone_rename_fingers[r'MiddleFinger1_\L'] = [
    r'Middle1_\L',
    r'M_1_\L',
    # 'Arm_\Left_Finger_3a',
    r'\LMid1',
    r'\LMiddle1N',
    r'F_Middle_01_\L',
    r'\L_Mid0',
    r'\L_Middle_01',
    r'\L_Middle1',
    r'\LeftHandMiddle1',
    r'\LeftFinger2',
    r'Finger3_2_\L',
    r'H_\L_Middle1',
    r'Bip_Middle_0_\L',
    r'Bip_\L_Finger2',
    r'\L_Fing3_A',
    r'\L_Middle_A',
    r'\L_Middle_A_1',
    r'Mf1_\L',
    'L_FINGER31',
    r'MiddleFinger1\L',
    r'\LFingerC1',
    r'MiddA_\L',
    r'\Lf_Middle1',
    r'Middle_01_\L',
    r'\L_Finger_C1',
    r'Middle01_\L',
    r'Arm_\Left_Finger_3_1',
    r'\L_Middlefinger_A',
    r'FingerA\LT_01',
    r'J_Bip_\L_Middle1',
    r'Bip_FMiddle00_\L',
    r'Arm_\Left_Finger_3a',
    r'J_Naka_A_\L',
    r'J_Mid_\L_1',
    r'\LHandMiddle',
    r'\LFinger2',
]
bone_rename_fingers[r'MiddleFinger2_\L'] = [
    r'Middle2_\L',
    r'M_2_\L',
    # 'Arm_\Left_Finger_3b',
    r'\LMid2',
    r'\LMiddle2N',
    r'F_Middle_02_\L',
    r'\L_Mid1',
    r'\L_Middle_02',
    r'\L_Middle2',
    r'\LeftHandMiddle2',
    r'\LeftFinger21',
    r'Finger3_3_\L',
    r'H_\L_Middle2',
    r'Bip_Middle_1_\L',
    r'Bip_\L_Finger21',
    r'\L_Fing3_B',
    r'\L_Middle_B',
    r'\L_Middle_B_1',
    r'Mf2_\L',
    'L_FINGER32',
    r'MiddleFinger2\L',
    r'\LFingerC2',
    r'MiddB_\L',
    r'\Lf_Middle2',
    r'Middle_02_\L',
    r'\L_Finger_C2',
    r'Middle02_\L',
    r'Arm_\Left_Finger_3_2',
    r'\L_Middlefinger_B',
    r'J_Bip_\L_Middle2',
    r'Bip_FMiddle01_\L',
    r'Arm_\Left_Finger_3b',
    r'J_Naka_B_\L',
    r'J_Mid_\L_2',
    r'\LHandMiddle1',
    r'\LFinger21',
]
bone_rename_fingers[r'MiddleFinger3_\L'] = [
    r'Middle3_\L',
    r'M_3_\L',
    # 'Arm_\Left_Finger_3c',
    r'\LMid3',
    r'\LMiddle3N',
    r'F_Middle_03_\L',
    r'\L_Mid2',
    r'\L_Middle_03',
    r'\LeftHandMiddle3',
    r'\LeftFinger22',
    r'Finger3_4_\L',
    r'H_\L_Middle3',
    r'Bip_Middle_2_\L',
    r'Bip_\L_Finger22',
    r'\L_Fing3_C',
    r'\L_Middle_C',
    r'\L_Middle_C_1',
    r'Mf3_\L',
    'L_FINGER33',
    r'MiddleFinger3\L',
    r'\LFingerC3',
    r'MiddC_\L',
    r'\Lf_Middle3',
    r'Middle_03_\L',
    r'\L_Finger_C3',
    r'Middle03_\L',
    r'Arm_\Left_Finger_3_3',
    r'\L_Middlefinger_C',
    r'FingerC\LT_01',
    r'J_Bip_\L_Middle3',
    r'Bip_FMiddle02_\L',
    r'Arm_\Left_Finger_3c',
    r'J_Naka_C_\L',
    r'J_Mid_\L_3',
    r'\LHandMiddle2',
    r'\LFinger22',
]
bone_rename_fingers[r'RingFinger1_\L'] = [
    r'Third1_\L',
    r'Ri_1_\L',
    # 'Arm_\Left_Finger_4a',
    r'\LRing1',
    r'\LRing1N',
    r'F_Ring_01_\L',
    r'\L_Ring0',
    r'\L_Ring_01',
    r'\LeftHandRing1',
    r'\LeftFinger3',
    r'Finger4_2_\L',
    r'H_\L_Ring1',
    r'Bip_Ring_0_\L',
    r'Bip_\L_Finger3',
    r'\L_Fing4_A',
    r'\L_Third_A',
    r'\L_Third_A_1',
    r'Rf1_\L',
    'L_FINGER41',
    r'ThirdFinger1\L',
    r'\LFingerB1',
    r'RingA_\L',
    r'Ring1_\L',
    r'\Lf_Ring1',
    r'Ring_01_\L',
    r'\L_Finger_D1',
    r'Ring01_\L',
    r'Arm_\Left_Finger_4_1',
    r'\L_Ringfinger_A',
    r'RingA\LT_01',
    r'J_Bip_\L_Ring1',
    r'Bip_FRing00_\L',
    r'Arm_\Left_Finger_4a',
    r'J_Kusu_A_\L',
    r'J_Ring_\L_1',
    r'\LHandRing',
    r'\LFinger3',
]
bone_rename_fingers[r'RingFinger2_\L'] = [
    r'Third2_\L',
    r'Ri_2_\L',
    # 'Arm_\Left_Finger_4b',
    r'\LRing2',
    r'\LRing2N',
    r'F_Ring_02_\L',
    r'\L_Ring1',
    r'\L_Ring_02',
    r'\LeftHandRing2',
    r'\LeftFinger31',
    r'Finger4_3_\L',
    r'H_\L_Ring2',
    r'Bip_Ring_1_\L',
    r'Bip_\L_Finger31',
    r'\L_Fing4_B',
    r'\L_Third_B',
    r'\L_Third_B_1',
    r'Rf2_\L',
    'L_FINGER42',
    r'ThirdFinger2\L',
    r'\LFingerB2',
    r'RingB_\L',
    r'Ring2_\L',
    r'\Lf_Ring2',
    r'Ring_02_\L',
    r'\L_Finger_D2',
    r'Ring02_\L',
    r'Arm_\Left_Finger_4_2',
    r'\L_Ringfinger_B',
    r'RingB\LT_01',
    r'J_Bip_\L_Ring2',
    r'Bip_FRing01_\L',
    r'Arm_\Left_Finger_4b',
    r'J_Kusu_B_\L',
    r'J_Ring_\L_2',
    r'\LHandRing1',
    r'\LFinger31',
]
bone_rename_fingers[r'RingFinger3_\L'] = [
    r'Third3_\L',
    r'Ri_3_\L',
    # 'Arm_\Left_Finger_4c',
    r'\LRing3',
    r'\LRing3N',
    r'F_Ring_03_\L',
    r'\L_Ring2',
    r'\L_Ring_03',
    r'\LeftHandRing3',
    r'\LeftFinger32',
    r'Finger4_4_\L',
    r'H_\L_Ring3',
    r'Bip_Ring_2_\L',
    r'Bip_\L_Finger32',
    r'\L_Fing4_C',
    r'\L_Third_C',
    r'\L_Third_C_1',
    r'Rf3_\L',
    'L_FINGER43',
    r'ThirdFinger3\L',
    r'\LFingerB3',
    r'RingC_\L',
    r'Ring3_\L',
    r'\Lf_Ring3',
    r'Ring_03_\L',
    r'\L_Finger_D3',
    r'Ring03_\L',
    r'Arm_\Left_Finger_4_3',
    r'\L_Ringfinger_C',
    r'RingC\LT_01',
    r'J_Bip_\L_Ring3',
    r'Bip_FRing02_\L',
    r'Arm_\Left_Finger_4c',
    r'J_Kusu_C_\L',
    r'J_Ring_\L_3',
    r'\LHandRing2',
    r'\LFinger32',
]
bone_rename_fingers[r'LittleFinger1_\L'] = [
    r'Little1_\L',
    r'Li_1_\L',
    # 'Arm_\Left_Finger_5a',
    r'\LPinky1',
    r'\LPinky1N',
    r'\LLittle1N',
    r'F_Pinky_01_\L',
    r'\L_Pinky0',
    r'\L_Pinkey_01',
    r'\LeftHandPinky1',
    r'\LeftFinger4',
    r'Finger5_2_\L',
    r'H_\L_Pinky1',
    r'Bip_Pinky_0_\L',
    r'Bip_\L_Finger4',
    r'\L_Fing5_A',
    r'\L_Little_A',
    r'\L_Little_A_1',
    r'Sf1_\L',
    'L_FINGER51',
    r'LittleFinger1\L',
    r'\LFingerA1',
    r'LittA_\L',
    r'Pinky1_\L',
    r'\Lf_Pinky1',
    r'Pinky_01_\L',
    r'\L_Finger_E1',
    r'Little01_\L',
    r'Arm_\Left_Finger_5_1',
    r'\L_Littlefinger_A',
    r'PinkyA\LT_01',
    r'J_Bip_\L_Little1',
    r'Bip_FPinky00_\L',
    r'Arm_\Left_Finger_5a',
    r'J_Ko_A_\L',
    r'J_Pinky_\L_1',
    r'\LHandPinky',
    r'\LFinger4',
]
bone_rename_fingers[r'LittleFinger2_\L'] = [
    r'Little2_\L',
    r'Li_2_\L',
    # 'Arm_\Left_Finger_5b',
    r'\LPinky2',
    r'\LPinky2N',
    r'\LLittle2N',
    r'F_Pinky_02_\L',
    r'\L_Pinky1',
    r'\L_Pinkey_02',
    r'\LeftHandPinky2',
    r'\LeftFinger41',
    r'Finger5_3_\L',
    r'H_\L_Pinky2',
    r'Bip_Pinky_1_\L',
    r'Bip_\L_Finger41',
    r'\L_Fing5_B',
    r'\L_Little_B',
    r'\L_Little_B_1',
    r'Sf2_\L',
    'L_FINGER52',
    r'LittleFinger2\L',
    r'\LFingerA2',
    r'LittB_\L',
    r'Pinky2_\L',
    r'\Lf_Pinky2',
    r'Pinky_02_\L',
    r'\L_Finger_E2',
    r'Little02_\L',
    r'Arm_\Left_Finger_5_2',
    r'\L_Littlefinger_B',
    r'PinkyB\LT_01',
    r'J_Bip_\L_Little2',
    r'Bip_FPinky01_\L',
    r'Arm_\Left_Finger_5b',
    r'J_Ko_B_\L',
    r'J_Pinky_\L_2',
    r'\LHandPinky1',
    r'\LFinger41',
]
bone_rename_fingers[r'LittleFinger3_\L'] = [
    r'Little3_\L',
    r'Li_3_\L',
    # 'Arm_\Left_Finger_5c',
    r'\LPinky3',
    r'\LPinky3N',
    r'\LLittle3N',
    r'F_Pinky_03_\L',
    r'\L_Pinky2',
    r'\L_Pinkey_03',
    r'\LeftHandPinky3',
    r'\LeftFinger42',
    r'Finger5_4_\L',
    r'H_\L_Pinky3',
    r'Bip_Pinky_2_\L',
    r'Bip_\L_Finger42',
    r'\L_Fing5_C',
    r'\L_Little_C',
    r'\L_Little_C_1',
    r'Sf3_\L',
    'L_FINGER53',
    r'LittleFinger3\L',
    r'\LFingerA3',
    r'LittC_\L',
    r'Pinky3_\L',
    r'\Lf_Pinky3',
    r'Pinky_03_\L',
    r'\L_Finger_E3',
    r'Little03_\L',
    r'Arm_\Left_Finger_5_3',
    r'\L_Littlefinger_C',
    r'PinkyC\LT_01',
    r'J_Bip_\L_Little3',
    r'Bip_FPinky02_\L',
    r'Arm_\Left_Finger_5c',
    r'J_Ko_C_\L',
    r'J_Pinky_\L_3',
    r'\LHandPinky2',
    r'\LFinger42',
]
